name: sigortamcepte

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Diğer bağımlılıklarınızı buraya ekleyin.

flutter:
  assets:
    - assets/
  # Diğer flutter konfigürasyonlarınızı buraya ekleyin.
