///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ClaimDetailsClaimDetailsAslob {
/*
{
  "code": "4",
  "shortDescription": "Motor",
  "longDescription": "Motor"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsAslob({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsAslob.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsSubLossType {
/*
{
  "code": "717",
  "shortDescription": "Motorlu Kara Taşıtları - Kasko",
  "longDescription": "Motorlu Kara Taşıtları - Kasko"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsSubLossType({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsSubLossType.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsCauseOfLoss {
/*
{
  "code": "11111",
  "shortDescription": "Çarpma",
  "longDescription": "Çarpma"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsCauseOfLoss({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsCauseOfLoss.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsLobCategory {
/*
{
  "code": "LB1",
  "shortDescription": "OTO",
  "longDescription": "OTO"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsLobCategory({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsLobCategory.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsClaimStatus {
/*
{
  "code": "OP",
  "shortDescription": "AÇIK",
  "longDescription": "AÇIK"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsClaimStatus({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsClaimStatus.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetailsPaymentDetailType {
/*
{
  "code": "558",
  "shortDescription": "TAZMİNAT",
  "longDescription": "TAZMİNAT"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetailsPaymentDetailType({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetailsPaymentDetailType.fromJson(
      Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetailsPaymentType {
/*
{
  "code": "5",
  "shortDescription": "TAZMİNAT",
  "longDescription": "TAZMİNAT"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetailsPaymentType({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetailsPaymentType.fromJson(
      Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetails {
/*
{
  "paymentDetailAmount": 5000,
  "paymentType": {
    "code": "5",
    "shortDescription": "TAZMİNAT",
    "longDescription": "TAZMİNAT"
  },
  "paymentDetailType": {
    "code": "558",
    "shortDescription": "TAZMİNAT",
    "longDescription": "TAZMİNAT"
  }
} 
*/

  int? paymentDetailAmount;
  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetailsPaymentType?
      paymentType;
  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetailsPaymentDetailType?
      paymentDetailType;

  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetails({
    this.paymentDetailAmount,
    this.paymentType,
    this.paymentDetailType,
  });
  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetails.fromJson(
      Map<String, dynamic> json) {
    paymentDetailAmount = json['paymentDetailAmount']?.toInt();
    paymentType = (json['paymentType'] != null)
        ? ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetailsPaymentType
            .fromJson(json['paymentType'])
        : null;
    paymentDetailType = (json['paymentDetailType'] != null)
        ? ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetailsPaymentDetailType
            .fromJson(json['paymentDetailType'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['paymentDetailAmount'] = paymentDetailAmount;
    if (paymentType != null) {
      data['paymentType'] = paymentType!.toJson();
    }
    if (paymentDetailType != null) {
      data['paymentDetailType'] = paymentDetailType!.toJson();
    }
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentMethod {
/*
{
  "code": "6",
  "shortDescription": "EFT / HAVALE",
  "longDescription": "EFT / HAVALE"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentMethod({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentMethod.fromJson(
      Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentFinalType {
/*
{
  "code": "03",
  "shortDescription": "SON ÖDEME",
  "longDescription": "SON ÖDEME"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentFinalType({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentFinalType.fromJson(
      Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentStatus {
/*
{
  "code": "SAV",
  "shortDescription": "İNCELEMEDE",
  "longDescription": "İNCELEMEDE"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentStatus({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentStatus.fromJson(
      Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetailsPaymentDataListPayeeDataPayeeRoleList {
/*
{
  "code": "CMT",
  "shortDescription": "HAK SAHİBİ",
  "longDescription": "HAK SAHİBİ"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPayeeDataPayeeRoleList({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPayeeDataPayeeRoleList.fromJson(
      Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetailsPaymentDataListPayeeData {
/*
{
  "bankAccountNumber": "T************************1",
  "payeeName": "İSİM SOYİSİM",
  "payeeRoleList": [
    {
      "code": "CMT",
      "shortDescription": "HAK SAHİBİ",
      "longDescription": "HAK SAHİBİ"
    }
  ]
} 
*/

  String? bankAccountNumber;
  String? payeeName;
  List<ClaimDetailsClaimDetailsLineDetailsPaymentDataListPayeeDataPayeeRoleList?>?
      payeeRoleList;

  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPayeeData({
    this.bankAccountNumber,
    this.payeeName,
    this.payeeRoleList,
  });
  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPayeeData.fromJson(
      Map<String, dynamic> json) {
    bankAccountNumber = json['bankAccountNumber']?.toString();
    payeeName = json['payeeName']?.toString();
    if (json['payeeRoleList'] != null) {
      final v = json['payeeRoleList'];
      final arr0 =
          <ClaimDetailsClaimDetailsLineDetailsPaymentDataListPayeeDataPayeeRoleList>[];
      v.forEach((v) {
        arr0.add(
            ClaimDetailsClaimDetailsLineDetailsPaymentDataListPayeeDataPayeeRoleList
                .fromJson(v));
      });
      payeeRoleList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['bankAccountNumber'] = bankAccountNumber;
    data['payeeName'] = payeeName;
    if (payeeRoleList != null) {
      final v = payeeRoleList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['payeeRoleList'] = arr0;
    }
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetailsPaymentDataList {
/*
{
  "paymentID": "DDAC590689944999",
  "paymentTotalAmount": 5000,
  "paymentCurrency": "TL",
  "paymentScheduleDate": "2021-11-15T00:00:00",
  "paymentPostDate": "1800-01-01T00:00:00",
  "payeeData": {
    "bankAccountNumber": "T************************1",
    "payeeName": "İSİM SOYİSİM",
    "payeeRoleList": [
      {
        "code": "CMT",
        "shortDescription": "HAK SAHİBİ",
        "longDescription": "HAK SAHİBİ"
      }
    ]
  },
  "paymentStatus": {
    "code": "SAV",
    "shortDescription": "İNCELEMEDE",
    "longDescription": "İNCELEMEDE"
  },
  "paymentFinalType": {
    "code": "03",
    "shortDescription": "SON ÖDEME",
    "longDescription": "SON ÖDEME"
  },
  "paymentMethod": {
    "code": "6",
    "shortDescription": "EFT / HAVALE",
    "longDescription": "EFT / HAVALE"
  },
  "paymentIssueDate": "2021-11-12T00:00:00",
  "paymentDetails": [
    {
      "paymentDetailAmount": 5000,
      "paymentType": {
        "code": "5",
        "shortDescription": "TAZMİNAT",
        "longDescription": "TAZMİNAT"
      },
      "paymentDetailType": {
        "code": "558",
        "shortDescription": "TAZMİNAT",
        "longDescription": "TAZMİNAT"
      }
    }
  ]
} 
*/

  String? paymentID;
  int? paymentTotalAmount;
  String? paymentCurrency;
  String? paymentScheduleDate;
  String? paymentPostDate;
  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPayeeData? payeeData;
  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentStatus?
      paymentStatus;
  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentFinalType?
      paymentFinalType;
  ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentMethod?
      paymentMethod;
  String? paymentIssueDate;
  List<ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetails?>?
      paymentDetails;

  ClaimDetailsClaimDetailsLineDetailsPaymentDataList({
    this.paymentID,
    this.paymentTotalAmount,
    this.paymentCurrency,
    this.paymentScheduleDate,
    this.paymentPostDate,
    this.payeeData,
    this.paymentStatus,
    this.paymentFinalType,
    this.paymentMethod,
    this.paymentIssueDate,
    this.paymentDetails,
  });
  ClaimDetailsClaimDetailsLineDetailsPaymentDataList.fromJson(
      Map<String, dynamic> json) {
    paymentID = json['paymentID']?.toString();
    paymentTotalAmount = json['paymentTotalAmount']?.toInt();
    paymentCurrency = json['paymentCurrency']?.toString();
    paymentScheduleDate = json['paymentScheduleDate']?.toString();
    paymentPostDate = json['paymentPostDate']?.toString();
    payeeData = (json['payeeData'] != null)
        ? ClaimDetailsClaimDetailsLineDetailsPaymentDataListPayeeData.fromJson(
            json['payeeData'])
        : null;
    paymentStatus = (json['paymentStatus'] != null)
        ? ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentStatus
            .fromJson(json['paymentStatus'])
        : null;
    paymentFinalType = (json['paymentFinalType'] != null)
        ? ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentFinalType
            .fromJson(json['paymentFinalType'])
        : null;
    paymentMethod = (json['paymentMethod'] != null)
        ? ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentMethod
            .fromJson(json['paymentMethod'])
        : null;
    paymentIssueDate = json['paymentIssueDate']?.toString();
    if (json['paymentDetails'] != null) {
      final v = json['paymentDetails'];
      final arr0 =
          <ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetails>[];
      v.forEach((v) {
        arr0.add(
            ClaimDetailsClaimDetailsLineDetailsPaymentDataListPaymentDetails
                .fromJson(v));
      });
      paymentDetails = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['paymentID'] = paymentID;
    data['paymentTotalAmount'] = paymentTotalAmount;
    data['paymentCurrency'] = paymentCurrency;
    data['paymentScheduleDate'] = paymentScheduleDate;
    data['paymentPostDate'] = paymentPostDate;
    if (payeeData != null) {
      data['payeeData'] = payeeData!.toJson();
    }
    if (paymentStatus != null) {
      data['paymentStatus'] = paymentStatus!.toJson();
    }
    if (paymentFinalType != null) {
      data['paymentFinalType'] = paymentFinalType!.toJson();
    }
    if (paymentMethod != null) {
      data['paymentMethod'] = paymentMethod!.toJson();
    }
    data['paymentIssueDate'] = paymentIssueDate;
    if (paymentDetails != null) {
      final v = paymentDetails;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['paymentDetails'] = arr0;
    }
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetailsClaimant {
/*
{
  "firstName": "İSİM",
  "middleName": "\t",
  "lastName": "SOYİSİM",
  "orgName": "\t",
  "fullName": "İSİM \t SOYİSİM",
  "identityNumber": "44444444444",
  "participantId": "64E7641CB1BD3E12"
} 
*/

  String? firstName;
  String? middleName;
  String? lastName;
  String? orgName;
  String? fullName;
  String? identityNumber;
  String? participantId;

  ClaimDetailsClaimDetailsLineDetailsClaimant({
    this.firstName,
    this.middleName,
    this.lastName,
    this.orgName,
    this.fullName,
    this.identityNumber,
    this.participantId,
  });
  ClaimDetailsClaimDetailsLineDetailsClaimant.fromJson(
      Map<String, dynamic> json) {
    firstName = json['firstName']?.toString();
    middleName = json['middleName']?.toString();
    lastName = json['lastName']?.toString();
    orgName = json['orgName']?.toString();
    fullName = json['fullName']?.toString();
    identityNumber = json['identityNumber']?.toString();
    participantId = json['participantId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['firstName'] = firstName;
    data['middleName'] = middleName;
    data['lastName'] = lastName;
    data['orgName'] = orgName;
    data['fullName'] = fullName;
    data['identityNumber'] = identityNumber;
    data['participantId'] = participantId;
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetailsCreatorOrgEntityUnit {
/*
{
  "code": "25",
  "shortDescription": "DİĞER BİRİM",
  "longDescription": "DİĞER BİRİM"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsLineDetailsCreatorOrgEntityUnit({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsLineDetailsCreatorOrgEntityUnit.fromJson(
      Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetailsLineTypeDescription {
/*
{
  "code": "1111111",
  "shortDescription": "Çarpma",
  "longDescription": "Çarpma"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsLineDetailsLineTypeDescription({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsLineDetailsLineTypeDescription.fromJson(
      Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetailsCauseOfLoss {
/*
{
  "code": "22222",
  "shortDescription": "Çarpma",
  "longDescription": "Çarpma"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsLineDetailsCauseOfLoss({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsLineDetailsCauseOfLoss.fromJson(
      Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetailsLineStatus {
/*
{
  "code": "05",
  "shortDescription": "AÇIK",
  "longDescription": "AÇIK"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsLineDetailsLineStatus({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsLineDetailsLineStatus.fromJson(
      Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetailsClaimantLine {
/*
{
  "code": "1111111",
  "shortDescription": "Çarpma",
  "longDescription": "Çarpma"
} 
*/

  String? code;
  String? shortDescription;
  String? longDescription;

  ClaimDetailsClaimDetailsLineDetailsClaimantLine({
    this.code,
    this.shortDescription,
    this.longDescription,
  });
  ClaimDetailsClaimDetailsLineDetailsClaimantLine.fromJson(
      Map<String, dynamic> json) {
    code = json['code']?.toString();
    shortDescription = json['shortDescription']?.toString();
    longDescription = json['longDescription']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['shortDescription'] = shortDescription;
    data['longDescription'] = longDescription;
    return data;
  }
}

class ClaimDetailsClaimDetailsLineDetails {
/*
{
  "createDate": "2021-02-19T15:25:05",
  "lineId": "AE3C494F3EA49E0D",
  "claimantLine": {
    "code": "1111111",
    "shortDescription": "Çarpma",
    "longDescription": "Çarpma"
  },
  "lineStatus": {
    "code": "05",
    "shortDescription": "AÇIK",
    "longDescription": "AÇIK"
  },
  "closeReason": "\t",
  "causeOfLoss": {
    "code": "22222",
    "shortDescription": "Çarpma",
    "longDescription": "Çarpma"
  },
  "estimatedLossAmount": 3000,
  "estimatedLossAmountCurrency": "TL",
  "coverageStatusCode": "20",
  "lineTypeDescription": {
    "code": "1111111",
    "shortDescription": "Çarpma",
    "longDescription": "Çarpma"
  },
  "claimantParticipantId": "64E7641CB1BD3E12",
  "coverId": "1111111",
  "subCoverId": "2222222",
  "productId": "3333333",
  "tkzCode": "\t",
  "coverageSBMType": "",
  "subrogationPotential": "Y",
  "creatorOrgEntityUnit": {
    "code": "25",
    "shortDescription": "DİĞER BİRİM",
    "longDescription": "DİĞER BİRİM"
  },
  "claimant": {
    "firstName": "İSİM",
    "middleName": "\t",
    "lastName": "SOYİSİM",
    "orgName": "\t",
    "fullName": "İSİM \t SOYİSİM",
    "identityNumber": "44444444444",
    "participantId": "64E7641CB1BD3E12"
  },
  "paymentDataList": [
    {
      "paymentID": "DDAC590689944999",
      "paymentTotalAmount": 5000,
      "paymentCurrency": "TL",
      "paymentScheduleDate": "2021-11-15T00:00:00",
      "paymentPostDate": "1800-01-01T00:00:00",
      "payeeData": {
        "bankAccountNumber": "T************************1",
        "payeeName": "İSİM SOYİSİM",
        "payeeRoleList": [
          {
            "code": "CMT",
            "shortDescription": "HAK SAHİBİ",
            "longDescription": "HAK SAHİBİ"
          }
        ]
      },
      "paymentStatus": {
        "code": "SAV",
        "shortDescription": "İNCELEMEDE",
        "longDescription": "İNCELEMEDE"
      },
      "paymentFinalType": {
        "code": "03",
        "shortDescription": "SON ÖDEME",
        "longDescription": "SON ÖDEME"
      },
      "paymentMethod": {
        "code": "6",
        "shortDescription": "EFT / HAVALE",
        "longDescription": "EFT / HAVALE"
      },
      "paymentIssueDate": "2021-11-12T00:00:00",
      "paymentDetails": [
        {
          "paymentDetailAmount": 5000,
          "paymentType": {
            "code": "5",
            "shortDescription": "TAZMİNAT",
            "longDescription": "TAZMİNAT"
          },
          "paymentDetailType": {
            "code": "558",
            "shortDescription": "TAZMİNAT",
            "longDescription": "TAZMİNAT"
          }
        }
      ]
    }
  ]
} 
*/

  String? createDate;
  String? lineId;
  ClaimDetailsClaimDetailsLineDetailsClaimantLine? claimantLine;
  ClaimDetailsClaimDetailsLineDetailsLineStatus? lineStatus;
  String? closeReason;
  ClaimDetailsClaimDetailsLineDetailsCauseOfLoss? causeOfLoss;
  int? estimatedLossAmount;
  String? estimatedLossAmountCurrency;
  String? coverageStatusCode;
  ClaimDetailsClaimDetailsLineDetailsLineTypeDescription? lineTypeDescription;
  String? claimantParticipantId;
  String? coverId;
  String? subCoverId;
  String? productId;
  String? tkzCode;
  String? coverageSBMType;
  String? subrogationPotential;
  ClaimDetailsClaimDetailsLineDetailsCreatorOrgEntityUnit? creatorOrgEntityUnit;
  ClaimDetailsClaimDetailsLineDetailsClaimant? claimant;
  List<ClaimDetailsClaimDetailsLineDetailsPaymentDataList?>? paymentDataList;

  ClaimDetailsClaimDetailsLineDetails({
    this.createDate,
    this.lineId,
    this.claimantLine,
    this.lineStatus,
    this.closeReason,
    this.causeOfLoss,
    this.estimatedLossAmount,
    this.estimatedLossAmountCurrency,
    this.coverageStatusCode,
    this.lineTypeDescription,
    this.claimantParticipantId,
    this.coverId,
    this.subCoverId,
    this.productId,
    this.tkzCode,
    this.coverageSBMType,
    this.subrogationPotential,
    this.creatorOrgEntityUnit,
    this.claimant,
    this.paymentDataList,
  });
  ClaimDetailsClaimDetailsLineDetails.fromJson(Map<String, dynamic> json) {
    createDate = json['createDate']?.toString();
    lineId = json['lineId']?.toString();
    claimantLine = (json['claimantLine'] != null)
        ? ClaimDetailsClaimDetailsLineDetailsClaimantLine.fromJson(
            json['claimantLine'])
        : null;
    lineStatus = (json['lineStatus'] != null)
        ? ClaimDetailsClaimDetailsLineDetailsLineStatus.fromJson(
            json['lineStatus'])
        : null;
    closeReason = json['closeReason']?.toString();
    causeOfLoss = (json['causeOfLoss'] != null)
        ? ClaimDetailsClaimDetailsLineDetailsCauseOfLoss.fromJson(
            json['causeOfLoss'])
        : null;
    estimatedLossAmount = json['estimatedLossAmount']?.toInt();
    estimatedLossAmountCurrency =
        json['estimatedLossAmountCurrency']?.toString();
    coverageStatusCode = json['coverageStatusCode']?.toString();
    lineTypeDescription = (json['lineTypeDescription'] != null)
        ? ClaimDetailsClaimDetailsLineDetailsLineTypeDescription.fromJson(
            json['lineTypeDescription'])
        : null;
    claimantParticipantId = json['claimantParticipantId']?.toString();
    coverId = json['coverId']?.toString();
    subCoverId = json['subCoverId']?.toString();
    productId = json['productId']?.toString();
    tkzCode = json['tkzCode']?.toString();
    coverageSBMType = json['coverageSBMType']?.toString();
    subrogationPotential = json['subrogationPotential']?.toString();
    creatorOrgEntityUnit = (json['creatorOrgEntityUnit'] != null)
        ? ClaimDetailsClaimDetailsLineDetailsCreatorOrgEntityUnit.fromJson(
            json['creatorOrgEntityUnit'])
        : null;
    claimant = (json['claimant'] != null)
        ? ClaimDetailsClaimDetailsLineDetailsClaimant.fromJson(json['claimant'])
        : null;
    if (json['paymentDataList'] != null) {
      final v = json['paymentDataList'];
      final arr0 = <ClaimDetailsClaimDetailsLineDetailsPaymentDataList>[];
      v.forEach((v) {
        arr0.add(
            ClaimDetailsClaimDetailsLineDetailsPaymentDataList.fromJson(v));
      });
      paymentDataList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['createDate'] = createDate;
    data['lineId'] = lineId;
    if (claimantLine != null) {
      data['claimantLine'] = claimantLine!.toJson();
    }
    if (lineStatus != null) {
      data['lineStatus'] = lineStatus!.toJson();
    }
    data['closeReason'] = closeReason;
    if (causeOfLoss != null) {
      data['causeOfLoss'] = causeOfLoss!.toJson();
    }
    data['estimatedLossAmount'] = estimatedLossAmount;
    data['estimatedLossAmountCurrency'] = estimatedLossAmountCurrency;
    data['coverageStatusCode'] = coverageStatusCode;
    if (lineTypeDescription != null) {
      data['lineTypeDescription'] = lineTypeDescription!.toJson();
    }
    data['claimantParticipantId'] = claimantParticipantId;
    data['coverId'] = coverId;
    data['subCoverId'] = subCoverId;
    data['productId'] = productId;
    data['tkzCode'] = tkzCode;
    data['coverageSBMType'] = coverageSBMType;
    data['subrogationPotential'] = subrogationPotential;
    if (creatorOrgEntityUnit != null) {
      data['creatorOrgEntityUnit'] = creatorOrgEntityUnit!.toJson();
    }
    if (claimant != null) {
      data['claimant'] = claimant!.toJson();
    }
    if (paymentDataList != null) {
      final v = paymentDataList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['paymentDataList'] = arr0;
    }
    return data;
  }
}

class ClaimDetailsClaimDetails {
/*
{
  "lineDetails": [
    {
      "createDate": "2021-02-19T15:25:05",
      "lineId": "AE3C494F3EA49E0D",
      "claimantLine": {
        "code": "1111111",
        "shortDescription": "Çarpma",
        "longDescription": "Çarpma"
      },
      "lineStatus": {
        "code": "05",
        "shortDescription": "AÇIK",
        "longDescription": "AÇIK"
      },
      "closeReason": "\t",
      "causeOfLoss": {
        "code": "22222",
        "shortDescription": "Çarpma",
        "longDescription": "Çarpma"
      },
      "estimatedLossAmount": 3000,
      "estimatedLossAmountCurrency": "TL",
      "coverageStatusCode": "20",
      "lineTypeDescription": {
        "code": "1111111",
        "shortDescription": "Çarpma",
        "longDescription": "Çarpma"
      },
      "claimantParticipantId": "64E7641CB1BD3E12",
      "coverId": "1111111",
      "subCoverId": "2222222",
      "productId": "3333333",
      "tkzCode": "\t",
      "coverageSBMType": "",
      "subrogationPotential": "Y",
      "creatorOrgEntityUnit": {
        "code": "25",
        "shortDescription": "DİĞER BİRİM",
        "longDescription": "DİĞER BİRİM"
      },
      "claimant": {
        "firstName": "İSİM",
        "middleName": "\t",
        "lastName": "SOYİSİM",
        "orgName": "\t",
        "fullName": "İSİM \t SOYİSİM",
        "identityNumber": "44444444444",
        "participantId": "64E7641CB1BD3E12"
      },
      "paymentDataList": [
        {
          "paymentID": "DDAC590689944999",
          "paymentTotalAmount": 5000,
          "paymentCurrency": "TL",
          "paymentScheduleDate": "2021-11-15T00:00:00",
          "paymentPostDate": "1800-01-01T00:00:00",
          "payeeData": {
            "bankAccountNumber": "T************************1",
            "payeeName": "İSİM SOYİSİM",
            "payeeRoleList": [
              {
                "code": "CMT",
                "shortDescription": "HAK SAHİBİ",
                "longDescription": "HAK SAHİBİ"
              }
            ]
          },
          "paymentStatus": {
            "code": "SAV",
            "shortDescription": "İNCELEMEDE",
            "longDescription": "İNCELEMEDE"
          },
          "paymentFinalType": {
            "code": "03",
            "shortDescription": "SON ÖDEME",
            "longDescription": "SON ÖDEME"
          },
          "paymentMethod": {
            "code": "6",
            "shortDescription": "EFT / HAVALE",
            "longDescription": "EFT / HAVALE"
          },
          "paymentIssueDate": "2021-11-12T00:00:00",
          "paymentDetails": [
            {
              "paymentDetailAmount": 5000,
              "paymentType": {
                "code": "5",
                "shortDescription": "TAZMİNAT",
                "longDescription": "TAZMİNAT"
              },
              "paymentDetailType": {
                "code": "558",
                "shortDescription": "TAZMİNAT",
                "longDescription": "TAZMİNAT"
              }
            }
          ]
        }
      ]
    }
  ],
  "policyCode": 701,
  "policyEndorsementNumber": 0,
  "policyOccurenceNumber": 4,
  "policyRenewalNumber": 0,
  "policyNumber": "1010960020",
  "claimNumber": "10109600200004",
  "claimStatus": {
    "code": "OP",
    "shortDescription": "AÇIK",
    "longDescription": "AÇIK"
  },
  "claimSource": "ASOS",
  "dateOfIncident": "2021-01-21T00:00:00",
  "dateReported": "2021-02-19T00:00:00",
  "lobCategory": {
    "code": "LB1",
    "shortDescription": "OTO",
    "longDescription": "OTO"
  },
  "causeOfLoss": {
    "code": "11111",
    "shortDescription": "Çarpma",
    "longDescription": "Çarpma"
  },
  "claimOwnerMail": "pdybhasar@anadolusigorta.com.tr",
  "subLossType": {
    "code": "717",
    "shortDescription": "Motorlu Kara Taşıtları - Kasko",
    "longDescription": "Motorlu Kara Taşıtları - Kasko"
  },
  "aslob": {
    "code": "4",
    "shortDescription": "Motor",
    "longDescription": "Motor"
  }
} 
*/

  List<ClaimDetailsClaimDetailsLineDetails?>? lineDetails;
  int? policyCode;
  int? policyEndorsementNumber;
  int? policyOccurenceNumber;
  int? policyRenewalNumber;
  String? policyNumber;
  String? claimNumber;
  ClaimDetailsClaimDetailsClaimStatus? claimStatus;
  String? claimSource;
  String? dateOfIncident;
  String? dateReported;
  ClaimDetailsClaimDetailsLobCategory? lobCategory;
  ClaimDetailsClaimDetailsCauseOfLoss? causeOfLoss;
  String? claimOwnerMail;
  ClaimDetailsClaimDetailsSubLossType? subLossType;
  ClaimDetailsClaimDetailsAslob? aslob;

  ClaimDetailsClaimDetails({
    this.lineDetails,
    this.policyCode,
    this.policyEndorsementNumber,
    this.policyOccurenceNumber,
    this.policyRenewalNumber,
    this.policyNumber,
    this.claimNumber,
    this.claimStatus,
    this.claimSource,
    this.dateOfIncident,
    this.dateReported,
    this.lobCategory,
    this.causeOfLoss,
    this.claimOwnerMail,
    this.subLossType,
    this.aslob,
  });
  ClaimDetailsClaimDetails.fromJson(Map<String, dynamic> json) {
    if (json['lineDetails'] != null) {
      final v = json['lineDetails'];
      final arr0 = <ClaimDetailsClaimDetailsLineDetails>[];
      v.forEach((v) {
        arr0.add(ClaimDetailsClaimDetailsLineDetails.fromJson(v));
      });
      lineDetails = arr0;
    }
    policyCode = json['policyCode']?.toInt();
    policyEndorsementNumber = json['policyEndorsementNumber']?.toInt();
    policyOccurenceNumber = json['policyOccurenceNumber']?.toInt();
    policyRenewalNumber = json['policyRenewalNumber']?.toInt();
    policyNumber = json['policyNumber']?.toString();
    claimNumber = json['claimNumber']?.toString();
    claimStatus = (json['claimStatus'] != null)
        ? ClaimDetailsClaimDetailsClaimStatus.fromJson(json['claimStatus'])
        : null;
    claimSource = json['claimSource']?.toString();
    dateOfIncident = json['dateOfIncident']?.toString();
    dateReported = json['dateReported']?.toString();
    lobCategory = (json['lobCategory'] != null)
        ? ClaimDetailsClaimDetailsLobCategory.fromJson(json['lobCategory'])
        : null;
    causeOfLoss = (json['causeOfLoss'] != null)
        ? ClaimDetailsClaimDetailsCauseOfLoss.fromJson(json['causeOfLoss'])
        : null;
    claimOwnerMail = json['claimOwnerMail']?.toString();
    subLossType = (json['subLossType'] != null)
        ? ClaimDetailsClaimDetailsSubLossType.fromJson(json['subLossType'])
        : null;
    aslob = (json['aslob'] != null)
        ? ClaimDetailsClaimDetailsAslob.fromJson(json['aslob'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (lineDetails != null) {
      final v = lineDetails;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['lineDetails'] = arr0;
    }
    data['policyCode'] = policyCode;
    data['policyEndorsementNumber'] = policyEndorsementNumber;
    data['policyOccurenceNumber'] = policyOccurenceNumber;
    data['policyRenewalNumber'] = policyRenewalNumber;
    data['policyNumber'] = policyNumber;
    data['claimNumber'] = claimNumber;
    if (claimStatus != null) {
      data['claimStatus'] = claimStatus!.toJson();
    }
    data['claimSource'] = claimSource;
    data['dateOfIncident'] = dateOfIncident;
    data['dateReported'] = dateReported;
    if (lobCategory != null) {
      data['lobCategory'] = lobCategory!.toJson();
    }
    if (causeOfLoss != null) {
      data['causeOfLoss'] = causeOfLoss!.toJson();
    }
    data['claimOwnerMail'] = claimOwnerMail;
    if (subLossType != null) {
      data['subLossType'] = subLossType!.toJson();
    }
    if (aslob != null) {
      data['aslob'] = aslob!.toJson();
    }
    return data;
  }
}

class ClaimDetails {
/*
{
  "claimDetails": {
    "lineDetails": [
      {
        "createDate": "2021-02-19T15:25:05",
        "lineId": "AE3C494F3EA49E0D",
        "claimantLine": {
          "code": "1111111",
          "shortDescription": "Çarpma",
          "longDescription": "Çarpma"
        },
        "lineStatus": {
          "code": "05",
          "shortDescription": "AÇIK",
          "longDescription": "AÇIK"
        },
        "closeReason": "\t",
        "causeOfLoss": {
          "code": "22222",
          "shortDescription": "Çarpma",
          "longDescription": "Çarpma"
        },
        "estimatedLossAmount": 3000,
        "estimatedLossAmountCurrency": "TL",
        "coverageStatusCode": "20",
        "lineTypeDescription": {
          "code": "1111111",
          "shortDescription": "Çarpma",
          "longDescription": "Çarpma"
        },
        "claimantParticipantId": "64E7641CB1BD3E12",
        "coverId": "1111111",
        "subCoverId": "2222222",
        "productId": "3333333",
        "tkzCode": "\t",
        "coverageSBMType": "",
        "subrogationPotential": "Y",
        "creatorOrgEntityUnit": {
          "code": "25",
          "shortDescription": "DİĞER BİRİM",
          "longDescription": "DİĞER BİRİM"
        },
        "claimant": {
          "firstName": "İSİM",
          "middleName": "\t",
          "lastName": "SOYİSİM",
          "orgName": "\t",
          "fullName": "İSİM \t SOYİSİM",
          "identityNumber": "44444444444",
          "participantId": "64E7641CB1BD3E12"
        },
        "paymentDataList": [
          {
            "paymentID": "DDAC590689944999",
            "paymentTotalAmount": 5000,
            "paymentCurrency": "TL",
            "paymentScheduleDate": "2021-11-15T00:00:00",
            "paymentPostDate": "1800-01-01T00:00:00",
            "payeeData": {
              "bankAccountNumber": "T************************1",
              "payeeName": "İSİM SOYİSİM",
              "payeeRoleList": [
                {
                  "code": "CMT",
                  "shortDescription": "HAK SAHİBİ",
                  "longDescription": "HAK SAHİBİ"
                }
              ]
            },
            "paymentStatus": {
              "code": "SAV",
              "shortDescription": "İNCELEMEDE",
              "longDescription": "İNCELEMEDE"
            },
            "paymentFinalType": {
              "code": "03",
              "shortDescription": "SON ÖDEME",
              "longDescription": "SON ÖDEME"
            },
            "paymentMethod": {
              "code": "6",
              "shortDescription": "EFT / HAVALE",
              "longDescription": "EFT / HAVALE"
            },
            "paymentIssueDate": "2021-11-12T00:00:00",
            "paymentDetails": [
              {
                "paymentDetailAmount": 5000,
                "paymentType": {
                  "code": "5",
                  "shortDescription": "TAZMİNAT",
                  "longDescription": "TAZMİNAT"
                },
                "paymentDetailType": {
                  "code": "558",
                  "shortDescription": "TAZMİNAT",
                  "longDescription": "TAZMİNAT"
                }
              }
            ]
          }
        ]
      }
    ],
    "policyCode": 701,
    "policyEndorsementNumber": 0,
    "policyOccurenceNumber": 4,
    "policyRenewalNumber": 0,
    "policyNumber": "1010960020",
    "claimNumber": "10109600200004",
    "claimStatus": {
      "code": "OP",
      "shortDescription": "AÇIK",
      "longDescription": "AÇIK"
    },
    "claimSource": "ASOS",
    "dateOfIncident": "2021-01-21T00:00:00",
    "dateReported": "2021-02-19T00:00:00",
    "lobCategory": {
      "code": "LB1",
      "shortDescription": "OTO",
      "longDescription": "OTO"
    },
    "causeOfLoss": {
      "code": "11111",
      "shortDescription": "Çarpma",
      "longDescription": "Çarpma"
    },
    "claimOwnerMail": "pdybhasar@anadolusigorta.com.tr",
    "subLossType": {
      "code": "717",
      "shortDescription": "Motorlu Kara Taşıtları - Kasko",
      "longDescription": "Motorlu Kara Taşıtları - Kasko"
    },
    "aslob": {
      "code": "4",
      "shortDescription": "Motor",
      "longDescription": "Motor"
    }
  }
} 
*/

  ClaimDetailsClaimDetails? claimDetails;

  ClaimDetails({
    this.claimDetails,
  });
  ClaimDetails.fromJson(Map<String, dynamic> json) {
    claimDetails = (json['claimDetails'] != null)
        ? ClaimDetailsClaimDetails.fromJson(json['claimDetails'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (claimDetails != null) {
      data['claimDetails'] = claimDetails!.toJson();
    }
    return data;
  }
}
