// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVSJfiitas8fjaVjljVCbISCxmitSM_mk',
    appId: '1:242003191694:web:ecac51991811dada5ba6df',
    messagingSenderId: '242003191694',
    projectId: 'anadolu-sigorta-bb9d7',
    authDomain: 'anadolu-sigorta-bb9d7.firebaseapp.com',
    storageBucket: 'anadolu-sigorta-bb9d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL1dHiZ-dswZTcPIf76317rYiXUY5FXQs',
    appId: '1:242003191694:android:2e4b6c605145d3755ba6df',
    messagingSenderId: '242003191694',
    projectId: 'anadolu-sigorta-bb9d7',
    storageBucket: 'anadolu-sigorta-bb9d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfBmQq-OTg4hePcEaogicKSpLznbBEwXY',
    appId: '1:242003191694:ios:8431ead612e140955ba6df',
    messagingSenderId: '242003191694',
    projectId: 'anadolu-sigorta-bb9d7',
    storageBucket: 'anadolu-sigorta-bb9d7.appspot.com',
    iosBundleId: 'com.example.sigortamcepte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfBmQq-OTg4hePcEaogicKSpLznbBEwXY',
    appId: '1:242003191694:ios:2ac0b64c2db9a1df5ba6df',
    messagingSenderId: '242003191694',
    projectId: 'anadolu-sigorta-bb9d7',
    storageBucket: 'anadolu-sigorta-bb9d7.appspot.com',
    iosBundleId: 'com.example.sigortamcepte.RunnerTests',
  );
}
